jobName: linux-bootconfig-presubmit-arm64
runIfChanged: ^build/lib/.*|Common.mk|projects/torvalds/linux/.*
cluster: prow-postsubmits-cluster
serviceaccountName: postsubmits-build-account
bucket: s3://prowdataclusterstack-316434458-prowbucket7c73355c-1n9f9v93wpjcm
architecture: ARM64
commands:
- if $(make check-project-path-exists); then make build -C $PROJECT_PATH; fi
projectPath: projects/torvalds/linux
envVars:
- name: ARTIFACTS_BUCKET
  value: s3://projectbuildpipeline-857-pipelineoutputartifactsb-10ajmk30khe3f
- name: BINARY_PLATFORMS
  value: linux/arm64
resources:
  requests:
    memory: 4Gi
    cpu: 1024m
