jobName: prometheus-node-exporter-tooling-presubmit
runIfChanged: EKS_DISTRO_BASE_TAG_FILE|^build/lib/.*|Common.mk|projects/prometheus/node_exporter/.*
branches:
- ^main$
commands:
- if $(make check-project-path-exists); then make build -C $PROJECT_PATH; fi
projectPath: projects/prometheus/node_exporter
imageBuild: true
resources:
  requests:
    memory: 16Gi
    cpu: 4