name: builder-baseimage-pr-notifier
on:
  pull_request_target:
    types: [opened]
jobs:
  builder-baseimage-pr-notifier:
    runs-on: ubuntu-latest
    
    if: ${{ contains(github.event.pull_request.title, 'Update builder-base') }}
    steps:
      - run: curl -d '{"key":"builder-base image"}' -X POST $SLACK_WEBHOOK
        env:
          SLACK_WEBHOOK : ${{ secrets.SLACK_WEBHOOK_URL }}
